# Generated by Django 4.2.20 on 2025-04-01 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("entidades", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostoCarregamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pc_morada", models.CharField(max_length=255)),
                ("pc_data_registo", models.DateField()),
                ("pc_intensidade_a", models.FloatField()),
                ("pc_intensidade_kw", models.FloatField()),
                ("pc_tipo_ligacao", models.IntegerField()),
                ("pc_preco_kwh", models.FloatField()),
                ("pc_estado", models.BooleanField()),
                (
                    "pc_img",
                    models.ImageField(
                        blank=True, max_length=255, null=True, upload_to=""
                    ),
                ),
                (
                    "pc_entidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="entidades.entidade",
                    ),
                ),
            ],
            options={
                "db_table": "PostoCarregamento",
            },
        ),
        migrations.CreateModel(
            name="IoTEquipamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iot_nome", models.CharField(max_length=55)),
                ("iot_data_registo", models.DateField()),
                ("iot_estado", models.BooleanField(default=False)),
                (
                    "iot_img",
                    models.ImageField(
                        blank=True, max_length=255, null=True, upload_to=""
                    ),
                ),
                (
                    "iot_posto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="postosCarregamento.postocarregamento",
                    ),
                ),
            ],
            options={
                "db_table": "IoTEquipamento",
            },
        ),
    ]
