# Generated by Django 4.2.20 on 2025-05-19 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("entidades", "0001_initial"),
        ("postosCarregamento", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="postocarregamento",
            old_name="pc_intensidade_kw",
            new_name="pc_potencia_kw",
        ),
        migrations.RemoveField(
            model_name="iotequipamento",
            name="iot_posto",
        ),
        migrations.AddField(
            model_name="iotequipamento",
            name="iot_output",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="iotequipamento",
            name="iot_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="postocarregamento",
            name="pc_iot_equipamento",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="postosCarregamento.iotequipamento",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Iot_Entidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="entidades.entidade",
                    ),
                ),
                (
                    "iot_equipamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="postosCarregamento.iotequipamento",
                    ),
                ),
            ],
            options={
                "db_table": "Iot_Entidade",
                "unique_together": {("iot_equipamento", "entidade")},
            },
        ),
    ]
