# Generated by Django 4.2.20 on 2025-04-01 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("utilizadores", "0001_initial"),
        ("postosCarregamento", "0001_initial"),
        ("automoveis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carregamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ca_data_inicio", models.DateField()),
                ("ca_data_fim", models.DateField()),
                ("ca_duracao", models.IntegerField()),
                ("ca_avg_v", models.FloatField()),
                ("ca_avg_a", models.FloatField()),
                ("ca_avg_kwh", models.FloatField()),
                ("ca_custo", models.FloatField()),
                (
                    "ca_carro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="automoveis.carro",
                    ),
                ),
                (
                    "ca_posto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="postosCarregamento.postocarregamento",
                    ),
                ),
                (
                    "ca_utilizador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="utilizadores.utilizador",
                    ),
                ),
            ],
            options={
                "db_table": "Carregamento",
            },
        ),
    ]
