# Generated by Django 4.2.21 on 2025-05-19 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("entidades", "0001_initial"),
        ("postosCarregamento", "0001_initial"),
        ("automoveis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carregamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ca_data_inicio", models.DateField()),
                ("ca_data_fim", models.DateField(blank=True, null=True)),
                ("ca_duracao", models.IntegerField(blank=True, null=True)),
                ("ca_avg_v", models.FloatField(blank=True, null=True)),
                ("ca_avg_a", models.FloatField(blank=True, null=True)),
                ("ca_avg_kwh", models.FloatField(blank=True, null=True)),
                ("ca_custo", models.FloatField(blank=True, null=True)),
                (
                    "ca_estado",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("ERROR", "Error"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "ultimos_dados",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "ca_Veiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="automoveis.veiculo",
                    ),
                ),
                (
                    "ca_entidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="entidades.entidade",
                    ),
                ),
                (
                    "ca_posto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="postosCarregamento.postocarregamento",
                    ),
                ),
            ],
            options={
                "db_table": "Carregamento",
            },
        ),
    ]
