# Generated by Django 4.2.20 on 2025-05-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carregamentos", "0003_alter_carregamento_ca_estado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carregamento",
            name="ca_data_fim",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="carregamento",
            name="ca_data_inicio",
            field=models.DateField(),
        ),
    ]
