# Generated by Django 4.2.20 on 2025-05-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carregamentos", "0005_remove_carregamento_ca_data_fim"),
    ]

    operations = [
        migrations.AddField(
            model_name="carregamento",
            name="ca_data_fim",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="carregamento",
            name="ca_data_inicio",
            field=models.DateTimeField(),
        ),
    ]
