# Generated by Django 4.2.20 on 2025-05-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carregamentos", "0007_remove_carregamento_ca_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="carregamento",
            name="ca_estado",
            field=models.IntegerField(
                choices=[("ACTIVE", 1), ("COMPLETED", 2), ("ERROR", 3)], default=1
            ),
        ),
    ]
