# Generated by Django 4.2.20 on 2025-04-01 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("utilizadores", "0001_initial"),
        ("entidades", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("c_marca", models.CharField(max_length=55)),
                ("c_modelo", models.CharField(max_length=55)),
                ("c_matricula", models.CharField(max_length=55, unique=True)),
                ("c_potencia", models.IntegerField()),
                ("c_ano_e_mes", models.DateField()),
                ("c_data_registo", models.DateField()),
                ("c_categoria", models.IntegerField()),
                ("c_estado", models.BooleanField()),
                (
                    "c_img",
                    models.ImageField(
                        blank=True, max_length=255, null=True, upload_to=""
                    ),
                ),
                (
                    "c_entidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="entidades.entidade",
                    ),
                ),
                (
                    "c_utilizador",
                    models.ManyToManyField(blank=True, to="utilizadores.utilizador"),
                ),
            ],
            options={
                "db_table": "Carro",
            },
        ),
        migrations.CreateModel(
            name="Anexos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("an_titulo", models.CharField(max_length=100)),
                ("an_data", models.DateField()),
                (
                    "an_anexo",
                    models.ImageField(
                        blank=True, max_length=255, null=True, upload_to=""
                    ),
                ),
                (
                    "an_carro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="automoveis.carro",
                    ),
                ),
            ],
            options={
                "db_table": "Anexos",
            },
        ),
    ]
