# Generated by Django 4.2.20 on 2025-05-27 15:15

from django.db import migrations, models
import django.db.models.deletion
import uploadFiles


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("entidades", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Anexos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "an_tipo",
                    models.IntegerField(
                        choices=[
                            (1, "Seguro"),
                            (2, "Inspeção"),
                            (3, "IUC"),
                            (4, "Outros"),
                        ],
                        default=4,
                    ),
                ),
                ("an_titulo", models.CharField(max_length=100)),
                ("an_data", models.DateField()),
                ("an_data_validade", models.DateField(blank=True, null=True)),
                (
                    "an_anexo",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to=uploadFiles.caminho_anexo_veiculo,
                    ),
                ),
            ],
            options={
                "db_table": "Anexos",
                "ordering": ["-an_data"],
            },
        ),
        migrations.CreateModel(
            name="Requisicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("r_motivo", models.TextField()),
                ("r_data_inicio", models.DateTimeField()),
                ("r_data_fim", models.DateTimeField(blank=True, null=True)),
                ("r_ilimitado", models.BooleanField(default=False)),
                (
                    "r_estado",
                    models.IntegerField(
                        choices=[
                            (1, "Pendente"),
                            (2, "Aprovada"),
                            (3, "Rejeitada"),
                            (4, "Terminada"),
                        ],
                        default=1,
                    ),
                ),
                ("r_motivo_terminacao", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "Requisicao",
                "ordering": ["-r_data_inicio"],
            },
        ),
        migrations.CreateModel(
            name="Veiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("v_modelo", models.CharField(blank=True, max_length=55, null=True)),
                ("v_marca", models.CharField(max_length=55)),
                ("v_cor", models.CharField(max_length=55)),
                ("v_matricula", models.CharField(max_length=55, unique=True)),
                ("v_potencia", models.IntegerField()),
                ("v_data_aquisicao", models.DateField()),
                (
                    "v_categoria",
                    models.IntegerField(
                        choices=[
                            (1, "Sedan"),
                            (2, "Citadino"),
                            (3, "SUV"),
                            (4, "Comercial"),
                            (5, "Utilitario"),
                        ]
                    ),
                ),
                (
                    "v_estado",
                    models.IntegerField(
                        choices=[
                            (1, "Disponivel"),
                            (2, "Em Manutencao"),
                            (3, "Avariado"),
                            (4, "Em uso"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "v_img",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to=uploadFiles.caminho_foto_veiculo,
                    ),
                ),
                ("v_assentos", models.IntegerField()),
                ("v_transmissao", models.CharField(max_length=55)),
                ("v_combustivel", models.CharField(max_length=55)),
                ("v_ano_matricula", models.DateField(blank=True, null=True)),
                ("v_quilometros", models.IntegerField(blank=True, null=True)),
                ("v_emissoes", models.IntegerField(blank=True, null=True)),
                (
                    "v_entidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="entidades.entidade",
                    ),
                ),
            ],
            options={
                "db_table": "Veiculo",
            },
        ),
        migrations.CreateModel(
            name="VeiculoEntidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="entidades.entidade",
                    ),
                ),
                (
                    "veiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="automoveis.veiculo",
                    ),
                ),
            ],
            options={
                "db_table": "VeiculoEntidade",
            },
        ),
    ]
