# Generated by Django 4.2.21 on 2025-05-19 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("entidades", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Anexos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("an_titulo", models.CharField(max_length=100)),
                ("an_data", models.DateField()),
                (
                    "an_anexo",
                    models.ImageField(
                        blank=True, max_length=255, null=True, upload_to=""
                    ),
                ),
            ],
            options={
                "db_table": "Anexos",
            },
        ),
        migrations.CreateModel(
            name="Veiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("v_modelo", models.CharField(blank=True, max_length=55, null=True)),
                ("v_marca", models.CharField(max_length=55)),
                ("v_cor", models.CharField(max_length=55)),
                ("v_matricula", models.CharField(max_length=55, unique=True)),
                ("v_potencia", models.IntegerField()),
                ("v_data_aquisicao", models.DateField()),
                ("v_data_registo", models.DateField()),
                ("v_categoria", models.IntegerField()),
                ("v_estado", models.BooleanField()),
                (
                    "v_img",
                    models.ImageField(
                        blank=True, max_length=255, null=True, upload_to=""
                    ),
                ),
                ("v_assentos", models.IntegerField()),
                ("v_transmissão", models.CharField(max_length=55)),
                ("v_combustivel", models.CharField(max_length=55)),
                (
                    "v_entidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="entidades.entidade",
                    ),
                ),
            ],
            options={
                "db_table": "Veiculo",
            },
        ),
    ]
