# Generated by Django 4.2.21 on 2025-06-03 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("entidades", "0001_initial"),
        ("automoveis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="veiculo",
            name="v_utilizador",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="requisicao",
            name="r_entidade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requisicoes",
                to="entidades.entidade",
            ),
        ),
        migrations.AddField(
            model_name="requisicao",
            name="r_utilizador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requisicoes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="requisicao",
            name="r_veiculo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requisicoes",
                to="automoveis.veiculo",
            ),
        ),
        migrations.AddField(
            model_name="anexos",
            name="an_veiculo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="automoveis.veiculo"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="requisicao",
            unique_together={("r_utilizador", "r_veiculo", "r_data_inicio")},
        ),
    ]
