# Generated by Django 4.2.20 on 2025-05-27 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("automoveis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="veiculo",
            name="v_utilizador",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="anexos",
            name="an_veiculo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="automoveis.veiculo"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="veiculoentidade",
            unique_together={("veiculo", "entidade")},
        ),
    ]
