# Generated by Django 4.2.21 on 2025-06-03 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("entidades", "0001_initial"),
        ("carregamentos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notificacoes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nt_data", models.DateField()),
                ("nt_titulo", models.CharField(max_length=255)),
                ("nt_mensagem", models.TextField()),
                ("nt_estado", models.BooleanField(default=False)),
                ("nt_tipo", models.IntegerField()),
                (
                    "nt_carregamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="carregamentos.carregamento",
                    ),
                ),
                (
                    "nt_entidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="entidades.entidade",
                    ),
                ),
            ],
            options={
                "db_table": "Notificacoes",
                "ordering": ["nt_data"],
            },
        ),
    ]
