# Generated by Django 4.2.20 on 2025-04-01 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Carregamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ca_data_inicio", models.DateField()),
                ("ca_data_fim", models.DateField()),
                ("ca_duracao", models.IntegerField()),
                ("ca_avg_v", models.FloatField()),
                ("ca_avg_a", models.FloatField()),
                ("ca_avg_kwh", models.FloatField()),
                ("ca_custo", models.FloatField()),
            ],
            options={
                "db_table": "Carregamento",
            },
        ),
        migrations.CreateModel(
            name="Entidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("e_nome", models.CharField(max_length=255)),
                ("e_email", models.EmailField(max_length=254, unique=True)),
                ("e_nif", models.CharField(max_length=255)),
                ("e_contacto", models.CharField(max_length=255)),
                ("e_morada", models.CharField(max_length=255)),
                ("e_ordem", models.CharField(max_length=255)),
                ("e_data_registo", models.DateField()),
            ],
            options={
                "db_table": "Entidade",
            },
        ),
        migrations.CreateModel(
            name="Utilizador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("u_nome", models.CharField(max_length=55)),
                ("u_password", models.CharField(max_length=255)),
                ("u_email", models.EmailField(max_length=254, unique=True)),
                ("u_data_registo", models.DateField()),
                ("u_tipo", models.IntegerField()),
                ("u_estado", models.BooleanField(default=False)),
                ("u_token", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "u_img_perfil",
                    models.ImageField(
                        blank=True, max_length=255, null=True, upload_to=""
                    ),
                ),
                (
                    "u_entidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapi.entidade"
                    ),
                ),
            ],
            options={
                "db_table": "Utilizador",
            },
        ),
        migrations.CreateModel(
            name="PostoCarregamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pc_morada", models.CharField(max_length=255)),
                ("pc_data_registo", models.DateField()),
                ("pc_intensidade_a", models.FloatField()),
                ("pc_intensidade_kw", models.FloatField()),
                ("pc_tipo_ligacao", models.IntegerField()),
                ("pc_preco_kwh", models.FloatField()),
                ("pc_estado", models.BooleanField()),
                (
                    "pc_img",
                    models.ImageField(
                        blank=True, max_length=255, null=True, upload_to=""
                    ),
                ),
                (
                    "pc_entidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapi.entidade"
                    ),
                ),
            ],
            options={
                "db_table": "PostoCarregamento",
            },
        ),
        migrations.CreateModel(
            name="Notificacoes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nt_data", models.DateField()),
                ("nt_titulo", models.CharField(max_length=255)),
                ("nt_mensagem", models.TextField()),
                ("nt_estado", models.BooleanField(default=False)),
                ("nt_tipo", models.IntegerField()),
                (
                    "nt_carregamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapi.carregamento",
                    ),
                ),
                (
                    "nt_entidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapi.entidade"
                    ),
                ),
                (
                    "nt_utilizador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapi.utilizador",
                    ),
                ),
            ],
            options={
                "db_table": "Notificacoes",
                "ordering": ["nt_data"],
            },
        ),
        migrations.CreateModel(
            name="IoTEquipamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iot_nome", models.CharField(max_length=55)),
                ("iot_data_registo", models.DateField()),
                ("iot_estado", models.BooleanField(default=False)),
                (
                    "iot_img",
                    models.ImageField(
                        blank=True, max_length=255, null=True, upload_to=""
                    ),
                ),
                (
                    "iot_posto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapi.postocarregamento",
                    ),
                ),
            ],
            options={
                "db_table": "IoTEquipamento",
            },
        ),
        migrations.CreateModel(
            name="Carro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("c_marca", models.CharField(max_length=55)),
                ("c_modelo", models.CharField(max_length=55)),
                ("c_matricula", models.CharField(max_length=55)),
                ("c_potencia", models.IntegerField()),
                ("c_ano_e_mes", models.DateField()),
                ("c_data_registo", models.DateField()),
                ("c_categoria", models.IntegerField()),
                ("c_estado", models.BooleanField()),
                (
                    "c_img",
                    models.ImageField(
                        blank=True, max_length=255, null=True, upload_to=""
                    ),
                ),
                (
                    "c_entidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapi.entidade"
                    ),
                ),
                (
                    "c_utilizador",
                    models.ManyToManyField(blank=True, to="myapi.utilizador"),
                ),
            ],
            options={
                "db_table": "Carro",
            },
        ),
        migrations.AddField(
            model_name="carregamento",
            name="ca_carro",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapi.carro"
            ),
        ),
        migrations.AddField(
            model_name="carregamento",
            name="ca_posto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="myapi.postocarregamento",
            ),
        ),
        migrations.AddField(
            model_name="carregamento",
            name="ca_utilizador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapi.utilizador"
            ),
        ),
        migrations.CreateModel(
            name="Anexos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("an_titulo", models.CharField(max_length=100)),
                ("an_data", models.DateField()),
                (
                    "an_anexo",
                    models.ImageField(
                        blank=True, max_length=255, null=True, upload_to=""
                    ),
                ),
                (
                    "an_carro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapi.carro"
                    ),
                ),
            ],
            options={
                "db_table": "Anexos",
            },
        ),
    ]
