# Generated by Django 4.2.20 on 2025-04-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("e_nome", models.CharField(max_length=255)),
                ("e_email", models.EmailField(max_length=254, unique=True)),
                ("e_nif", models.CharField(max_length=255)),
                ("e_contacto", models.CharField(max_length=255)),
                ("e_morada", models.CharField(max_length=255)),
                ("e_ordem", models.CharField(max_length=255)),
                ("e_data_registo", models.DateField()),
            ],
            options={
                "db_table": "Entidade",
            },
        ),
    ]
