# Generated by Django 4.2.20 on 2025-04-01 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("entidades", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Utilizador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("u_nome", models.CharField(max_length=55)),
                ("u_password", models.CharField(max_length=255)),
                ("u_email", models.EmailField(max_length=254, unique=True)),
                ("u_data_registo", models.DateField()),
                ("u_tipo", models.IntegerField()),
                ("u_estado", models.BooleanField(default=False)),
                ("u_token", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "u_img_perfil",
                    models.ImageField(
                        blank=True, max_length=255, null=True, upload_to=""
                    ),
                ),
                (
                    "u_entidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="entidades.entidade",
                    ),
                ),
            ],
            options={
                "db_table": "Utilizador",
            },
        ),
    ]
