# Generated by Django 4.2.20 on 2025-04-06 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("utilizadores", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="utilizador",
            name="u_email",
        ),
        migrations.RemoveField(
            model_name="utilizador",
            name="u_nome",
        ),
    ]
