# Generated by Django 4.2.20 on 2025-04-06 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("utilizadores", "0002_remove_utilizador_u_email_remove_utilizador_u_nome"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="utilizador",
            name="u_data_registo",
        ),
    ]
