# Generated by Django 4.2.21 on 2025-05-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utilizadores", "0003_remove_utilizador_u_data_registo"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilizador",
            name="u_departamento",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
