# Generated by Django 4.2.21 on 2025-05-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utilizadores", "0004_utilizador_u_departamento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utilizador",
            name="u_img_perfil",
            field=models.ImageField(blank=True, null=True, upload_to="fotos_perfil/"),
        ),
    ]
